---
title: Personalized number
max_points: 10
instructions: |
  <h1>Personalized number</h1>
  <p>
    Your personalized exercise is a number. You must submit the number
    incremented by one.
  </p>
view_type: access.types.stdasync.acceptPost
fields:
  - name: solution
    title: Solution
    required: True

#template: sample_course/exercises/personalized_number/template.html

personalized: True
generated_files:
  - file: number
    key: number
    content_in_template: True
    url_in_template: True
    allow_download: True
generator:
  cmd: [ "python3", "generator.py" ]
  cwd: sample_course/exercises/personalized_number/
max_submissions_before_regeneration: 3

actions:
  - type: grader.actions.prepare
    expect_success: True
    cp_generated: number->user/number
#    cp_generated: ./->user/
#    cp_personal: orignumber->user/orignumber
#    cp_personal: ./->user/
# cp_personal assumes that the personal file (orignumber) exists in the personal directory
# even before the first submission has been received from the student
    cp_exercises: exercises/personalized_number->user
  - title: Check solution
    type: grader.actions.sandbox
    cmd: [ "python3", "check_number.py" ]
# test store_user_files action, it is not really useful for this exercise
  - type: grader.actions.store_user_files
    cp: user/number->orignumber
